"""add daily riddle tables

Revision ID: e1916bfaaef4
Revises: d1e2f3a4b5c6
Create Date: 2026-02-20 13:07:58.032509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1916bfaaef4'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='new_stability'
    )
    op.create_table('triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('img_path', sa.String(length=512), nullable=True),
    sa.Column('wiki_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'source', name='triggers_unique_name_source'),
    schema='new_stability'
    )
    op.create_table('daily_riddles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('riddle', sa.Text(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('release_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_edited_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='new_stability'
    )
    op.create_table('daily_riddles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('riddle', sa.Text(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image_link', sa.String(length=512), nullable=True),
    sa.Column('release_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_edited_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['new_stability.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='new_stability'
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['new_stability.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='teams_unique_name_per_event'),
    schema='new_stability'
    )
    op.create_table('tiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('img_src', sa.String(length=512), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['new_stability.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'index', name='tiles_unique_index_per_event'),
    schema='new_stability'
    )
    op.create_table('daily_riddle_solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('riddle_id', sa.UUID(), nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['riddle_id'], ['daily_riddles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['event_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'team_id', 'riddle_id', name='riddle_solutions_unique_event_team_riddle')
    )
    op.create_table('daily_riddle_solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('riddle_id', sa.UUID(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['riddle_id'], ['new_stability.daily_riddles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['new_stability.teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'riddle_id', name='riddle_solutions_unique_team_riddle'),
    schema='new_stability'
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('require_all', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['new_stability.tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='new_stability'
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['new_stability.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='team_members_unique_user_per_team'),
    schema='new_stability'
    )
    op.create_table('tile_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('tile_id', sa.UUID(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['new_stability.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tile_id'], ['new_stability.tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'tile_id', name='tile_statuses_unique_team_tile'),
    schema='new_stability'
    )
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('parent_challenge_id', sa.UUID(), nullable=True),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('require_all', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('count_per_action', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_challenge_id'], ['new_stability.challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['new_stability.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['new_stability.triggers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='new_stability'
    )
    op.create_table('task_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['new_stability.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['new_stability.teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'task_id', name='task_statuses_unique_team_task'),
    schema='new_stability'
    )
    op.create_table('challenge_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['new_stability.challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['new_stability.teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'challenge_id', name='challenge_statuses_unique_team_challenge'),
    schema='new_stability'
    )
    op.create_table('challenge_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_status_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('img_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['new_stability.actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenge_status_id'], ['new_stability.challenge_statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_status_id', 'action_id', name='challenge_proofs_unique_status_action'),
    schema='new_stability'
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('bingo_challenges', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bingo_tiles', ['tile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bingo_tiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('boss_dictionary', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('clan_points_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('diary_applications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'diary_content', ['target_diary_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('diary_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'diary_content', ['diary_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_team_member_mappings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'event_teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_teams', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['captain'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_trigger_mappings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'event_triggers', ['trigger_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('raid_tier_application', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'raid_tiers', ['target_raid_tier_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('raid_tier_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'raid_tiers', ['target_raid_tier_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('raid_tiers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['tier_name', 'tier_order'])

    with op.batch_alter_table('sp3_event_tile_challenge_mapping', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'event_challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'sp3_event_tiles', ['tile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sp3_event_tiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'sp3_regions', ['region_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sp3_regions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('time_split_applications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['discord_id'], ondelete='CASCADE')

    with op.batch_alter_table('time_splits_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['submitter_id'], ['discord_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'boss_dictionary', ['boss'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['discord_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('time_splits_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('time_split_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sp3_regions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sp3_event_tiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sp3_event_tile_challenge_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('raid_tiers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('raid_tier_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('raid_tier_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('event_trigger_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('event_teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('event_team_member_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('diary_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('diary_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('clan_points_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('boss_dictionary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bingo_tiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bingo_challenges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('challenge_proofs', schema='new_stability')
    op.drop_table('challenge_statuses', schema='new_stability')
    op.drop_table('task_statuses', schema='new_stability')
    op.drop_table('challenges', schema='new_stability')
    op.drop_table('tile_statuses', schema='new_stability')
    op.drop_table('team_members', schema='new_stability')
    op.drop_table('tasks', schema='new_stability')
    op.drop_table('daily_riddle_solutions', schema='new_stability')
    op.drop_table('daily_riddle_solutions')
    op.drop_table('tiles', schema='new_stability')
    op.drop_table('teams', schema='new_stability')
    op.drop_table('daily_riddles', schema='new_stability')
    op.drop_table('actions', schema='new_stability')
    op.drop_table('daily_riddles')
    op.drop_table('triggers', schema='new_stability')
    op.drop_table('events', schema='new_stability')
    # ### end Alembic commands ###
