name: Run Pytest on Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: stability
          POSTGRES_PASSWORD: stabilisite
          POSTGRES_DB: stability
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U stability"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U stability; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Run Pytest
        env:
          DATABASE_USERNAME: stability
          DATABASE_PASSWORD: stabilisite
          DATABASE_URL: localhost:5432/stability
        run: |
          pytest
